### ISSUE TITLE
Support for connectX-3 pro vpi?

### ISSUE THREAD

**Issue by xyhuang** [Mellanox/k8s-rdma-sriov-dev-plugin#13]
Hi, for connectX-3 pro vpi devices, is there any chance it could work with kubernetes? It seems from https://community.mellanox.com/docs/DOC-3153 that it only supports connectX-4/5...

**Comment by moshe010** [comment]
ConnectX3 are not supported by the plugin. I recommend you to upgrade to ConnectX4 or 5. They bring lot of features that will be useful for rdma and nic

**Comment by xyhuang** [comment]
ok thanks
