### ISSUE TITLE
how can i get ib library in container?

### ISSUE THREAD

**Issue by Eric-918** [Mellanox/k8s-rdma-sriov-dev-plugin#17]
hi, guys, how can i get ib library in container?
need i copy libib*.so* to my docker image or this plugin already do this work ?

**Comment by paravmellanox** [comment]
@Eric-918 , ib library are part of the pre build container image for mofed4.4 here.
https://hub.docker.com/r/mellanox/mlnx_ofed_linux-4.4-1.0.0.0-centos7.4/
If you wish to create your own docker image, you can use this sample Dockerfiles here.

https://github.com/Mellanox/mofed_dockerfiles

**Comment by Eric-918** [comment]
thx, this solve my problem

**Comment by paravmellanox** [comment]
@Eric-918 great. Can you please close the issue?
