### ISSUE TITLE
How to write Dockerfile to use vhca in container?

### ISSUE THREAD

**Issue by flymark2010** [Mellanox/k8s-rdma-sriov-dev-plugin#4]
Hi, I want to communicate with RDMA between containers. I created two Pods with image `mellanox/centos_7_2_mofed_4_4_0_1_9_0`, then tested with `ib_send_bw` command. Everything goes fine. So could you please share the Dockerfile for `mellanox/centos_7_2_mofed_4_4_0_1_9_0`? Thanks!

**Comment by paravmellanox** [comment]
@flymark2010 sure. I will upload it soon hopefully today.

**Comment by paravmellanox** [comment]
@flymark2010 , please find the Dockerfiles at below repository.
It took a while since our internal and external paths are different.

https://github.com/Mellanox/mofed_dockerfiles

I closed the issue, but please reopen in case if you see any issues.
