### ISSUE TITLE
The performance of vhca?

### ISSUE THREAD

**Issue by flymark2010** [Mellanox/k8s-rdma-sriov-dev-plugin#8]
Is the performance(bindwidth and latency) same with the physical hca or is just `1/numvfs` times of the physical hca performance?

**Comment by paravmellanox** [comment]
@flymark2010 this is probably not the right forum to discuss the vendor specific performance. Please contact mellanox support for it.

**Comment by flymark2010** [comment]
OK, sorry for that.
